### ISSUE TITLE
Methone is affected by the styles in the embedding page

### ISSUE THREAD

**Issue by danielsson** [datasektionen/Methone#7]
Most likely this means that we should only use divs and spans, in order to minimize the risk of attracting careless styles.

**Comment by danielsson** [comment]
We could also decide that its it the responsibility of the implementors to avoid styling the bar.

**Comment by macfeaster** [comment]
I agree with your first comment — use only general elements like divs and spans to avoid collision with for example nav. That, together with prefixing all classes and IDs, should be enough to avoid collisions. If elements still collide, it would then be because of careless styling by the implementor.

Also, if the implementors need to use any custom styling (like 50px margin top on all their page content), that should be documented.

**Comment by danielsson** [comment]
+1

**Comment by danielsson** [comment]
Fixed in 7ba5af17921e70409e5bc1560607c308f3a582e8
